source 'https://rubygems.org'

gem 'bourbon'
gem 'neat'
gem 'bitters'
gem 'leaflet-rails'
gem 'middleman', '~> 4.3'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-gh-pages'
gem 'middleman-livereload'
gem 'middleman-sprockets'
